### ISSUE TITLE
Can you please remove global state?

### ISSUE THREAD

**Issue by peterbourgon** [honeycombio/libhoney-go#11] opened 2017-04-19 12:20 UTC
I would like to use this library in a project that will handle multiple concurrent writers with multiple WriteKeys. At the moment it's not possible, because the package uses a single global txClient, along with some other global state, configured with a single global Config object, to orchestrate remote writes. But there's no reason this can't work in practice: rather than using a singleton, you just need to bundle the relevant state into data types, constructed with constructors. That is,

```go
type Writer struct {
    client txClient
    // ...
}

func NewWriter(config Config) (*Writer, error) {
    // ...
}

func (w *Writer) Send(e Event) error {
    // ...
}
```

Speaking generally—and _mea culpa_ for quoting myself here, but—"[package global state has the illusion](http://peter.bourgon.org/go-best-practices-2016/#program-design) of convenience, but it’s a false economy: doing so breaks code modularity, makes it more difficult for developers or future maintainers to understand dependency relationships, and makes writing independent, parallelizable tests [or satisfying more complex user needs] much more difficult." More pithily: [packages should store declarations](https://twitter.com/peterbourgon/status/833620924163321856); only components should store state.

Thanks for considering :)

**Comment by maplebed** [comment] 2017-04-19 17:42
Hi! Thank you for this issue.  I'd like to address your comment in two parts.

First, the simple. For the specific use you are describing (multiple write keys) it will work as intended in its current state.  You can set the write key globally or on a `Builder` or on a specific `Event` and it will be correctly split into its own batch for transmission to Honeycomb. More generally, for the problem you're describing (multiple areas of code within your application, each of which is writing to a different team), using a `Builder` is the best approach for this library.  They are functionally what you're describing as a `Writer` - they each have their own config, construct their own events, and when those events are dispatched to Honeycomb, wind up in their own batches. If you've tried this and it doesn't work, it's definitely a bug.

Second, about package global state, in general I agree with you. And I believe, actually, that this library could change the internal implementation to use a txClient per Builder without actually changing the semantics of its use. However, given the limited resources of our team, combined with the functionality you actually need being already available, I hope you can understand that changing the internal implementation is low on our list of priorities. 

Thank you for the links to your blog - it was good reading.  I am sure there's a place this library could get to that would combine a number of your tips - sane defaults that do the right thing while still getting rid of any global state. Hopefully, it eventually will. Until then, though, I'd like to close this issue as "will not fix".

-ben

**Comment by peterbourgon** [comment] 2017-04-20 07:11
Thanks for the reply. I guess I was a bit lazy in my original post; I also want to maintain multiple independent connections to Honeycomb, one per team key. But I appreciate your position, and I'm happy to use the API myself. Thanks for the detailed reply.

**Comment by maplebed** [comment] 2017-04-20 14:09
Ah! Yes, that makes sense. The HTTP RoundTripper is exposed as something you can replace - it instead of the default there you provide something that does pooling or connection management based on the X-Honeycomb-Team header I think you will achieve your goal. And of course, using the API directly as you mentioned is always an option.

**Comment by maplebed** [comment] 2019-02-22 17:04
With the introduction of a `Client` object, there is now a way of isolating different sending queues (thereby maintaining multiple independent connections to Honeycomb) and you can pretend that there is no package-level state. Considering this fixed.

**Closed** 2019-02-22 17:04 UTC
